### PR TITLE
mflash: fix build with gcc 9.1.0

### PR DESCRIPTION
**Pull request by sztsian**
Source: http://openocd.zylin.com/gitweb?p=openocd.git;a=commitdiff;h=f7e624fa7112e9e673011f75c23f812d5f89420c
mflash: fix build with gcc 9.1.0

With new gcc we get compile time error:
	In function ‘mg_gen_ataid’,
	    inlined from ‘mg_storage_config’ at src/flash/mflash.c:1174:2:
	src/flash/mflash.c:1162:2: error: ‘memset’ offset [509, 512] from the
	 object at ‘buff’ is out of the bounds of referenced subobject
	 ‘reserved7’ with type ‘mg_io_uint8[186]’ {aka ‘unsigned char[186]’}
	 at offset 322 [-Werror=array-bounds]
	1162 |  memset(pSegIdDrvInfo->reserved7, 0x00, 190);

Since its first submission in 2009, mflash code has this field
	mg_io_uint8 reserved7[186];
that is memset for 190 bytes, clearly overflowing.
The 4 bytes after reserved7[] in the struct belong to fields that
are not used, so the overflow is not damaging anything, but is
probably a crap way to initialize them too.

Reduce the memset parameter to stay within the array size.
Explicitly initialize the remaining fields so the behaviour is
not changed.
Add a comment for the field "re_of_hw_rst" that is the only one
not properly initialized. Bug?

Change-Id: I6f637cc800d61d4365575be07b7f50e73bdd0ca5
Signed-off-by: Antonio Borneo <borneo.antonio@gmail.com>

### CODE REVIEW

**Comment by sztsian** [comment]
Without this patch, riscv-openocd cannot build on Fedora 30.
